// BE/config/errorCodes.js
// Master error codes file - Single source of truth for all error codes

const ERROR_CODES = {
    // Validation Errors (VAL_xxx)
    VAL_EMAIL_REQUIRED: 'VAL_EMAIL_REQUIRED',
    VAL_PASSWORD_REQUIRED: 'VAL_PASSWORD_REQUIRED',
    VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',
    VAL_PASSWORD_TOO_SHORT: 'VAL_PASSWORD_TOO_SHORT',
    VAL_USERNAME_REQUIRED: 'VAL_USERNAME_REQUIRED',
    VAL_USERNAME_TOO_SHORT: 'VAL_USERNAME_TOO_SHORT',
    VAL_USERNAME_TOO_LONG: 'VAL_USERNAME_TOO_LONG',
    VAL_USERNAME_INVALID_FORMAT: 'VAL_USERNAME_INVALID_FORMAT',
    VAL_USERNAME_TAKEN: 'VAL_USERNAME_TAKEN',
    VAL_EMAIL_TAKEN: 'VAL_EMAIL_TAKEN',
    VAL_COUNTRY_REQUIRED: 'VAL_COUNTRY_REQUIRED',
    VAL_GENDER_REQUIRED: 'VAL_GENDER_REQUIRED',
    VAL_ALL_FIELDS_REQUIRED: 'VAL_ALL_FIELDS_REQUIRED',
    
    // Authentication Errors (AUTH_xxx)
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    AUTH_ACCOUNT_DELETED: 'AUTH_ACCOUNT_DELETED',
    AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
    
    // System Errors (SYS_xxx)
    SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
    SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
    SYS_DATABASE_CONNECTION_FAILED: 'SYS_DATABASE_CONNECTION_FAILED',
    SYS_SERVER_ERROR: 'SYS_SERVER_ERROR',
    SYS_MAINTENANCE: 'SYS_MAINTENANCE',
    
    // Network Errors (NET_xxx)
    NET_CONNECTION_ERROR: 'NET_CONNECTION_ERROR',
    NET_TIMEOUT: 'NET_TIMEOUT',
    NET_SERVER_UNREACHABLE: 'NET_SERVER_UNREACHABLE',
    
    // Rate Limiting Errors (RATE_xxx)
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    RATE_TOO_MANY_REQUESTS: 'RATE_TOO_MANY_REQUESTS',
    RATE_TOO_MANY_LOGIN_ATTEMPTS: 'RATE_TOO_MANY_LOGIN_ATTEMPTS',
    
    // User Settings Errors (SETTINGS_xxx)
    SETTINGS_COUNTRY_CHANGE_RESTRICTED: 'SETTINGS_COUNTRY_CHANGE_RESTRICTED',
    SETTINGS_INVALID_PROFILE_PHOTO: 'SETTINGS_INVALID_PROFILE_PHOTO',
    SETTINGS_FILE_TOO_LARGE: 'SETTINGS_FILE_TOO_LARGE',
    SETTINGS_INVALID_FILE_TYPE: 'SETTINGS_INVALID_FILE_TYPE',
    
    // Mood Tracking Errors (MOOD_xxx)
    MOOD_INVALID: 'MOOD_INVALID',
    MOOD_ALREADY_RECORDED: 'MOOD_ALREADY_RECORDED',
    MOOD_REQUIRED: 'MOOD_REQUIRED',
    
    // Contact Form Errors (CONTACT_xxx)
    CONTACT_SUBJECT_REQUIRED: 'CONTACT_SUBJECT_REQUIRED',
    CONTACT_MESSAGE_REQUIRED: 'CONTACT_MESSAGE_REQUIRED',
    CONTACT_EMAIL_REQUIRED: 'CONTACT_EMAIL_REQUIRED',
    
    // Generic/Unknown Errors
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    OPERATION_FAILED: 'OPERATION_FAILED'
  };
  
  module.exports = { ERROR_CODES };